sudo: required

language: java

services:
    - docker

before_install:
    - docker build -t serveur -f Dockerfile .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push clausg/m1_devops_projet;
    fi
