FROM maven:3.5-jdk-7-onbuild

LABEL maintainer "GuiΩ <guillaume.claus@worldonline.fr>"

COPY target/M1_DevOps_projet_clausg-1.0.jar projet.jar
COPY wait-for-it.sh wait-for-it.sh

EXPOSE 5342

ENTRYPOINT ["java", "-cp", "projet.jar", "clausg_projet.client.AppClient" "serveur" "5342"]
