FROM maven:3.3-jdk-8-onbuild

LABEL maintainer "GuiΩ <guillaume.claus@worldonline.fr>"

COPY target/M1_DevOps_projet_clausg-1.0.jar projet.jar

EXPOSE 5342

ENTRYPOINT ["java", "-cp", "projet.jar", "clausg_projet.client.AppClient"]
